---
collections:
  - name: community.vmware
    version: 5.2.0
  - name: ansible.utils
    version: 5.1.2
  - name: community.general
    version: 10.2.0
  - name: rhsgsa.openshift
    version: 1.0.0
