---
collections:
  - name: community.vmware
    version: 1.12.0
  - name: redhat.openshift
    version: 1.3.0
  - name: ansible.utils
    version: 2.7.0
  - name: community.general
    version: 7.4.0
