---
- name: Gather VM datastore information from vCenter
  hosts: localhost
  gather_facts: no
  
  tasks:
    - name: Gather VM information
      community.vmware.vmware_guest_info:
        hostname: "{{ vcenter_host }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_password }}"
        name: "{{ vm_name }}"
      register: vm_info

    - name: Extract datastore information
      set_fact:
        datastores: "{{ vm_info.instance.datastore | map(attribute='name') | list }}"

    - name: Display datastore information
      debug:
        msg: "VM '{{ vm_name }}' is using the following datastores: {{ datastores | join(', ') }}"
