- name: Test Galaxy Connection
  hosts: localhost
  tasks:
    - name: Download a Role from Ansible Galaxy
      ansible.builtin.command:
        cmd: "ansible-galaxy collection install community.vmware"
