---
- name: Gather VM datastore information from vCenter
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Gather VM information
      community.vmware.vmware_vm_info:
        hostname: "{{ vcenter_host }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_password }}"
        name: "{{ vm_name }}"
      delegate_to: localhost
      register: vm_info
    
    - debug:
    	var: vm_info.virtual_machines
