---
- name: Gather VM datastore information from vCenter
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Build a list of all the datastores
      vmware.vmware_rest.vcenter_datastore_info:
      register: all_the_datastores

    - name: Capture the datastore id
      set_fact:
        datastore_id: "{{ all_the_datastores.value[0].datastore }}"
