---
- name: Test Connectivity to vCenter
  hosts: localhost
  gather_facts: no
  tasks:
  
    - name: Check DNS Resolution
      ansible.builtin.command: nslookup {{ vcenter_hostname }}
      register: dns_result
      ignore_errors: yes

    - name: Debug DNS Resolution
      ansible.builtin.debug:
        var: dns_result.stdout

    - name: Test HTTPS Connectivity to vCenter
      ansible.builtin.uri:
        url: https://{{ vcenter_hostname }}
        method: GET
        timeout: 10
        validate_certs: no
      register: connectivity_result
      ignore_errors: yes

    - name: Debug HTTPS Connectivity Result
      ansible.builtin.debug:
        var: connectivity_result

    # Optional: Use ping to see if the vCenter is reachable
    - name: Test ICMP Ping to vCenter
      ansible.builtin.command: ping -c 4 {{ vcenter_hostname }}
      register: ping_result
      ignore_errors: yes
  
    - name: Debug ICMP Ping Result
      ansible.builtin.debug:
        var: ping_result.stdout
