    - name: Fetch detailed information about VMs
      vmware.vmware_rest.vcenter_vm_info:
        vcenter_hostname: "{{ vcenter_hostname }}"
        vcenter_username: "{{ vcenter_username }}"
        vcenter_password: "{{ vcenter_password }}"
        vcenter_validate_certs: yes
        vm: "{{ user_selected_vm_list }}"
      register: vm_details
