- name: Convert user-selected VM names to list
  ansible.builtin.set_fact:
    user_selected_vm_list: "{{ user_selected_vm_names.split('\n') | map('trim') }}"

- name: Build a list of all the folders
  vmware.vmware_rest.vcenter_folder_info:
  register: all_folders

- name: Filter VM folders
  ansible.builtin.set_fact:
    vm_folders: "{{ all_folders.value | selectattr('type', 'equalto', 'VIRTUAL_MACHINE') | list }}"

- name: Check each VM folder for VMs to include user selections only
  vmware.vmware_rest.vcenter_vm_info:
    folders: "{{ item.folder }}"
  register: vm_folders_with_vms
  loop: "{{ vm_folders }}"
  when: vm_folders | length > 0

- name: Debug VM information fetched
  ansible.builtin.debug:
    msg: "{{ vm_folders_with_vms.results }}"

- name: Initialize an empty list for vms_details
  ansible.builtin.set_fact:
    vms_details: []

- name: Collect details of user-selected VMs
  ansible.builtin.set_fact:
    vms_details: "{{ vms_details + [item] }}"
  loop: "{{ vm_folders_with_vms.results | map(attribute='value') | flatten }}"
  when: item.name in user_selected_vm_list
  loop_control:
    label: "{{ item.name }}"

# Step 7: Query network and datastore information
- name: Query network information for selected VMs
  vmware.vmware_rest.vcenter_vm_network_info:
    vm: "{{ item.vm }}"
  register: network_info
  loop: "{{ vms_details }}"

- name: Query datastore information for selected VMs
  vmware.vmware_rest.vcenter_vm_storage_info:
    vm: "{{ item.vm }}"
  register: datastore_info
  loop: "{{ vms_details }}"

# Step 8: Collect network and datastore ids from VMs details
- name: Initialize an empty list for network_ids
  ansible.builtin.set_fact:
    network_ids: []

- name: Initialize an empty list for datastore_ids
  ansible.builtin.set_fact:
    datastore_ids: []

- name: Collect network ids
  ansible.builtin.set_fact:
    network_ids: "{{ network_ids + [item] }}"
  loop: "{{ network_info.results | map(attribute='network') | flatten }}"  # adapt appropriate attributes  

- name: Collect datastore ids
  ansible.builtin.set_fact:
    datastore_ids: "{{ datastore_ids + [item] }}"
  loop: "{{ datastore_info.results | map(attribute='datastore') | flatten }}"  # adapt appropriate attributes  

- name: Ensure network_ids and datastore_ids are captured properly
  ansible.builtin.debug:
    msg: "Network IDs: {{ network_ids }}, Datastore IDs: {{ datastore_ids }}"

- name: Debug selected VMs details
  ansible.builtin.debug:
    msg: "{{ vms_details }}"

