- name: Convert user-selected VM names to list
  ansible.builtin.set_fact:
    user_selected_vm_list: "{{ user_selected_vm_names.split('\n') }}"

- name: Build a list of all the folders
  vmware.vmware_rest.vcenter_folder_info:
  register: all_folders

- name: Filter VM folders
  ansible.builtin.set_fact:
    vm_folders: "{{ all_folders.value | selectattr('type', 'equalto', 'VIRTUAL_MACHINE') | list }}"

- name: Check each VM folder for VMs
  vmware.vmware_rest.vcenter_vm_info:
    folders: "{{ item.folder }}"
  register: vm_folders_with_vms
  loop: "{{ vm_folders }}"
  when: vm_folders | length > 0

- name: Collect details of user-selected VMs
  ansible.builtin.set_fact:
    vm_name_id_pairs: "{{ vm_name_id_pairs | default([]) + [{'name': vm.name, 'vm': vm.vm, 'network': vm.network, 'datastore': vm.datastore}] }}"
  loop: "{{ vm_folders_with_vms.results | map(attribute='value') | flatten }}"
  loop_control:
    loop_var: vm
  when: vm.name in user_selected_vm_list

- name: Prepare VMs for Plan spec
  ansible.builtin.set_fact:
    vms_for_plan_spec: "{{ vms_for_plan_spec | default([]) + [{'hooks': [], 'id': vm_id.vm}] }}"
  loop: "{{ vm_name_id_pairs }}"
  loop_control:
    loop_var: vm_id

- name: Ensure vm_name_id_pairs are populated
  ansible.builtin.debug:
    msg: "{{ vm_name_id_pairs }}"

- name: Get information for Networks and Datastores
  ansible.builtin.set_fact:
    network_ids: "{{ vm_name_id_pairs | map(attribute='network') | flatten | unique }}"
    datastore_ids: "{{ vm_name_id_pairs | map(attribute='datastore') | flatten | unique }}"

- name: Ensure network_ids and datastore_ids are captured properly
  ansible.builtin.debug:
    msg: "Network IDs: {{ network_ids }}, Datastore IDs: {{ datastore_ids }}"

- name: Set Network ID
  ansible.builtin.set_fact:
    portgroup_id: "{{ item }}"
  loop: "{{ network_ids }}"

- name: Create or update a NetworkMap
  redhat.openshift.k8s:
    state: present
    definition:
      apiVersion: forklift.konveyor.io/v1beta1
      kind: NetworkMap
      metadata:
        name: "{{ networkmap_name }}-{{ loop.index }}"
        namespace: apm0002135-non-prod
      spec:
        map:
          - destination:
              type: pod
            source:
              id: "{{ portgroup_id }}"
        provider:
          destination:
            name: local-cluster
            namespace: apm0002135-non-prod
          source:
            name: "{{ provider_name }}"
            namespace: apm0002135-non-prod
  loop: "{{ network_ids }}"

- name: Set Datastore ID
  ansible.builtin.set_fact:
    datastore_id: "{{ item }}"
  loop: "{{ datastore_ids }}"

- name: Create or update a StorageMap
  redhat.openshift.k8s:
    state: present
    definition:
      apiVersion: forklift.konveyor.io/v1beta1
      kind: StorageMap
      metadata:
        name: "{{ storagemap_name }}-{{ loop.index }}"
        namespace: apm0002135-non-prod
      spec:
        map:
          - destination:
              storageClass: portworx-rwx-kubevirt
            source:
              id: "{{ datastore_id }}"
        provider:
          destination:
            name: local-cluster
            namespace: apm0002135-non-prod
          source:
            name: "{{ provider_name }}"
            namespace: apm0002135-non-prod
  loop: "{{ datastore_ids }}"

- name: Deploy Virt Plan
  redhat.openshift.k8s:
    state: present
    definition:
      apiVersion: forklift.konveyor.io/v1beta1
      kind: Plan
      metadata:
        name: "{{ plan_name }}"
        namespace: apm0002135-non-prod
      spec:
        archived: false
        description: ''
        map:
          network:
            name: "{{ networkmap_name }}"
            namespace: apm0002135-non-prod
          storage:
            name: "{{ storagemap_name }}"
            namespace: apm0002135-non-prod
        provider:
          destination:
            name: local-cluster
            namespace: apm0002135-non-prod
          source:
            name: "{{ provider_name }}"
            namespace: apm0002135-non-prod
        targetNamespace: apm0002135-non-prod
        vms: "{{ vms_for_plan_spec }}"
        warm: false

- name: Create a Migration manifest to run the Plan CR
  redhat.openshift.k8s:
    api_version: forklift.konveyor.io/v1beta1
    kind: Migration
    namespace: apm0002135-non-prod
    name: "{{ plan_name }}"
    definition:
      metadata:
        name: "{{ plan_name }}"
        namespace: apm0002135-non-prod
      spec:
        plan:
          name: "{{ plan_name }}"
          namespace: apm0002135-non-prod
