    - name: Fetch detailed information about VMs
      vmware.vmware_rest.vcenter_vm_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        filter:
          names: "{{ user_selected_vm_list }}"
      register: vm_details
