- name: Convert user-selected VM names to list
  ansible.builtin.set_fact:
    user_selected_vm_list: "{{ user_selected_vm_names.split('\n') }}"

- name: Build a list of all the folders
  vmware.vmware_rest.vcenter_folder_info:
  register: all_folders

- name: Filter VM folders
  ansible.builtin.set_fact:
    vm_folders: "{{ all_folders.value | selectattr('type', 'equalto', 'VIRTUAL_MACHINE') | list }}"

- name: Check each VM folder for VMs to include user selections only
  vmware.vmware_rest.vcenter_vm_info:
    folders: "{{ item.folder }}"
  register: vm_folders_with_vms
  loop: "{{ vm_folders }}"
  when: vm_folders | length > 0

- name: Debug VM information fetched
  ansible.builtin.debug:
    msg: "{{ vm_folders_with_vms.results }}"

- name: Initialize an empty list for vms_details
  ansible.builtin.set_fact:
    vms_details: []

- name: Collect details of user-selected VMs
  ansible.builtin.set_fact:
    vms_details: "{{ vms_details + [vm for vm in item.value if vm.name in user_selected_vm_list] }}"
  loop: "{{ vm_folders_with_vms.results }}"
  loop_control:
    label: "{{ item.folders }}"
