---
# Step 1: Convert User-Selected VM Names to List
- name: Convert user-selected VM names to list
  ansible.builtin.set_fact:
    user_selected_vm_list: "{{ user_selected_vm_names.split('\n') | map('trim') }}"

- name: Debug user_selected_vm_list
  ansible.builtin.debug:
    msg: "{{ user_selected_vm_list }}"

# Step 2: Fetch Detailed Information about VMs
- name: Fetch detailed information about VMs
  vmware.vmware_rest.vcenter_vm_info:
    vcenter_hostname: "{{ vcenter_hostname }}"
    vcenter_username: "{{ vcenter_username }}"
    vcenter_password: "{{ vcenter_password }}"
    vcenter_validate_certs: no
    names: "{{ user_selected_vm_list }}"
  delegate_to: localhost
  register: vm_details

- name: Debug vm_details
  ansible.builtin.debug:
    msg: "{{ vm_details }}"

# Step 3: Initialize lists for network_ids and datastore_ids
- name: Initialize lists for network_ids and datastore_ids
  ansible.builtin.set_fact:
    network_ids: []
    datastore_ids: []

# Step 4: Fetch Network Information using vmware_guest_info (vmware.vmware)
- name: Fetch network information for selected VMs
  vmware.vmware.guest_info:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    name: "{{ item.name }}"
  delegate_to: localhost
  register: network_info
  loop: "{{ vm_details.value }}"
  loop_control:
    label: "{{ item.name }}"

# Consolidate Network IDs
- name: Collect network ids
  ansible.builtin.set_fact:
    network_ids: "{{ network_ids + network_info.network_interfaces | map(attribute='network') | list }}"

# Step 5: Fetch Datastore Information
- name: Fetch datastore information
  vmware.vmware_rest.vcenter_datastore_info:
    vcenter_hostname: "{{ vcenter_hostname }}"
    vcenter_username: "{{ vcenter_username }}"
    vcenter_password: "{{ vcenter_password }}"
    vcenter_validate_certs: no
  delegate_to: localhost
  register: datastore_info

- name: Debug datastore_info
  ansible.builtin.debug:
    msg: "{{ datastore_info }}"

# Step 6: Collect Datastore IDs
- name: Collect datastore ids
  ansible.builtin.set_fact:
    datastore_ids: "{{ datastore_ids + [item.datastore] }}"
  loop: "{{ datastore_info.value }}"
  when: "'{{ item.datastore }}' in (vm_details.value | map(attribute='datastore') | list flatten())"

- name: Ensure network_ids and datastore_ids are captured properly
  ansible.builtin.debug:
    msg: "Network IDs: {{ network_ids | unique }}, Datastore IDs: {{ datastore_ids | unique }}"

# Step 7: Create or Update NetworkMap for Each Unique Network
- name: Create or update a NetworkMap for each unique network
  redhat.openshift.k8s:
    state: present
    definition:
      apiVersion: forklift.konveyor.io/v1beta1
      kind: NetworkMap
      metadata:
        name: "{{ networkmap_name }}-{{ loop.index }}"
        namespace: apm0002135-non-prod
      spec:
        map:
          - destination:
              type: pod
            source:
              id: "{{ item }}"
        provider:
          destination:
            name: local-cluster
            namespace: apm0002135-non-prod
          source:
            name: vmware
            namespace: apm0002135-non-prod
  loop: "{{ network_ids | unique }}"
  loop_control:
    label: "{{ item }}"

# Step 8: Create or Update StorageMap for Each Unique Datastore
- name: Create or update a StorageMap for each unique datastore
  redhat.openshift.k8s:
    state: present
    definition:
      apiVersion: forklift.konveyor.io/v1beta1
      kind: StorageMap
      metadata:
        name: "{{ storagemap_name }}-{{ loop.index }}"
        namespace: apm0002135-non-prod
      spec:
        map:
          - destination:
              storageClass: portworx-rwx-kubevirt
            source:
              id: "{{ item }}"
        provider:
          destination:
            name: local-cluster
            namespace: apm0002135-non-prod
          source:
            name: vmware
            namespace: apm0002135-non-prod
  loop: "{{ datastore_ids | unique }}"
  loop_control:
    label: "{{ item }}"

# Step 9: Prepare VMs for Plan Spec
- name: Prepare VMs for Plan spec
  ansible.builtin.set_fact:
    vms_for_plan_spec: "{{ vms_for_plan_spec | default([]) + [{'hooks': [], 'id': vm.vm}] }}"
  loop: "{{ vm_details.value }}"
  loop_control:
    loop_var: vm

# Step 10: Deploy Virt Plan
- name: Deploy Virt Plan
  redhat.openshift.k8s:
    state: present
    definition:
      apiVersion: forklift.konveyor.io/v1beta1
      kind: Plan
      metadata:
        name: "{{ plan_name }}"
        namespace: apm0002135-non-prod
      spec:
        archived: false
        description: ''
        map:
         
