- name: Deploy Provider resource
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: forklift.konveyor.io/v1beta1
      kind: Provider
      metadata:
        name: "{{ provider_name }}"
        namespace: "{{ provider_namespace }}"
      spec:
        secret:
          name: "{{ vmware_credentials }}"
          namespace: "{{ provider_namespace }}"
        settings:
          vddkInitImage: 'image-registry.openshift-image-registry.svc:5000/openshift-mtv/vddk:8.0.3'
        type: vsphere
        url: 'https://{{ vmware_host }}/sdk'

